# yaml-language-server: $schema=./quartz/plugins/quartz-plugins.schema.json
configuration:
  pageTitle: CharlotteWrites
  pageTitleSuffix: ""
  enableSPA: true
  enablePopovers: true
  analytics:
    provider: google
    tagId: G-EGM46TNG5B
  locale: it-IT
  baseUrl: charlottewrites.eu
  ignorePatterns:
    - private
    - templates
    - .obsidian
  theme:
    fontOrigin: googleFonts
    cdnCaching: true
    typography:
      header: Schibsted Grotesk
      body: Source Sans Pro
      code: IBM Plex Mono
    colors:
      lightMode:
        light: "#faf8f5"
        lightgray: "#eee9df"
        gray: "#cbd2d9"
        darkgray: "#111827"
        dark: "#0f172a"
        secondary: "#7b2880"
        tertiary: "#9c39a1"
        highlight: rgba(167, 84, 169, 0.15)
        textHighlight: "#f3c4f588"
      darkMode:
        light: "#030611"
        lightgray: "#0c1222"
        gray: "#1c2840"
        darkgray: "#e2c6e3"
        dark: "#d48bd6"
        secondary: "#A754A9"
        tertiary: "#d48bd6"
        highlight: rgba(167, 84, 169, 0.25)
        textHighlight: "#a754a955"
plugins:
  - source: "@quartz-community/created-modified-date"
    enabled: true
    options:
      defaultDateType: created
      priority:
        - frontmatter
        - git
        - filesystem
    order: 10
  - source: "@quartz-community/syntax-highlighting"
    enabled: true
    options:
      theme:
        light: github-light
        dark: github-dark
      keepBackground: false
    order: 20
  - source: "@quartz-community/obsidian-flavored-markdown"
    enabled: true
    options:
      enableInHtmlEmbed: false
      enableCheckbox: true
    order: 30
  - source: "@quartz-community/github-flavored-markdown"
    enabled: true
    order: 40
  - source: "@quartz-community/table-of-contents"
    enabled: true
    order: 50
    layout:
      position: left
      priority: 35
  - source: "@quartz-community/crawl-links"
    enabled: true
    options:
      markdownLinkResolution: shortest
    order: 60
  - source: "@quartz-community/description"
    enabled: true
    order: 70
  - source: "@quartz-community/latex"
    enabled: true
    options:
      renderEngine: katex
    order: 80
  - source: "@quartz-community/citations"
    enabled: false
    order: 85
  - source: "@quartz-community/hard-line-breaks"
    enabled: false
    order: 90
  - source: "@quartz-community/ox-hugo"
    enabled: false
    order: 91
  - source: "@quartz-community/roam"
    enabled: false
    order: 92
  - source: "@quartz-community/quartz-fonts"
    enabled: true
  - source: "@quartz-themes/core"
    enabled: false
    options:
      theme: tokyo-night
      mode: both
  - source: "@quartz-community/remove-draft"
    enabled: true
  - source: "@quartz-community/explicit-publish"
    enabled: false
  - source: "@quartz-community/unlisted-pages"
    enabled: true
    options: {}
    order: 45
  - source: "@quartz-community/encrypted-pages"
    enabled: false
  - source: "@quartz-community/stacked-pages"
    enabled: false
    layout:
      position: afterBody
      priority: 50
      display: all
  - source: "@quartz-community/alias-redirects"
    enabled: true
  - source: "@quartz-community/content-index"
    enabled: true
    layout:
      position: right
      priority: 70
      display: desktop-only
    options:
      enableSiteMap: true
      enableRSS: true
  - source: "@quartz-community/favicon"
    enabled: true
  - source: "@quartz-community/og-image"
    enabled: true
  - source: "@quartz-community/cname"
    enabled: true
  - source: "@quartz-community/canvas-page"
    enabled: true
  - source: "@quartz-community/content-page"
    enabled: true
  - source: "@quartz-community/folder-page"
    enabled: true
  - source: "@quartz-community/tag-page"
    enabled: true
  - source: "@quartz-community/explorer"
    enabled: true
    layout:
      position: left
      priority: 40
      display: desktop-only
  - source: "@quartz-community/explorer"
    enabled: true
    layout:
      position: header
      priority: 40
      display: mobile-only
      group: toolbar
  - source: "@quartz-community/graph"
    enabled: true
    options:
      linkDistance: 45
      repelForce: 0.7
      fontSize: 0.7
    layout:
      position: afterBody
      priority: 10
  - source: "@quartz-community/search"
    enabled: true
    layout:
      position: header
      priority: 10
      group: toolbar
      groupOptions:
        grow: true
        align: center
  - source: "@quartz-community/backlinks"
    enabled: true
    layout:
      position: right
      priority: 50
  - source: "@quartz-community/article-title"
    enabled: true
    layout:
      position: beforeBody
      priority: 10
  - source: "@quartz-community/content-meta"
    enabled: true
    layout:
      position: beforeBody
      priority: 20
  - source: "@quartz-community/tag-list"
    enabled: false
    layout:
      position: beforeBody
      priority: 30
  - source: "@quartz-community/page-title"
    enabled: true
    layout:
      position: header
      priority: 10
  - source: "@quartz-community/darkmode"
    enabled: true
    layout:
      position: head
      priority: 20
      group: toolbar
      groupOptions:
        align: center
  - source: "@quartz-community/reader-mode"
    enabled: true
    layout:
      position: header
      priority: 30
      group: toolbar
      groupOptions:
        align: center
  - source: "@quartz-community/breadcrumbs"
    enabled: true
    layout:
      position: beforeBody
      priority: 5
      condition: not-index
  - source: "@quartz-community/comments"
    enabled: true
    options:
      provider: giscus
      options:
        repo: nooutis/quartz
        repoId: R_kgDOTsdz1w
        category: Comments
        categoryId: DIC_kwDOTsdz184DClZ0
        mapping: url
        strict: true
        reactionsEnabled: true
        inputPosition: bottom
        lightTheme: light-theme
        darkTheme: dark
        lang: en
    layout:
      position: afterBody
      priority: 10
  - source: "@quartz-community/footer"
    enabled: true
    options:
      links:
        Instagram: https://www.instagram.com/ch4rlott3_reads?igsh=MWcwYmdyam03aWR6eA%3D%3D&utm_source=qr
        Substack: https://substack.com/@charlotter3ads
        YouTube: https://www.youtube.com/@oytismand
    layout:
      position: footer
      priority: 50
  - source: "@quartz-community/recent-notes"
    enabled: true
    options:
      title: Recent Notes
      limit: 3
      linkToMore: false
      showTags: true
    layout:
      position: left
      priority: 25
      display: desktop-only
  - source: "@quartz-community/recent-notes"
    enabled: true
    options:
      title: Recent Notes
      limit: 3
      linkToMore: false
      showTags: true
    layout:
      position: footer
      priority: 25
      display: mobile-only 
  - source: "@quartz-community/spacer"
    enabled: true
    options: {}
    order: 25
    layout:
      position: left
      priority: 25
      display: mobile-only
  - source: "@quartz-community/bases-page"
    enabled: true
    options: {}
    order: 50
  - source: "@quartz-community/note-properties"
    enabled: true
    options:
      includeAll: false
      includedProperties:
        - description
        - tags
        - aliases
      excludedProperties: []
      hidePropertiesView: false
      delimiters: ---
      language: yaml
    order: 5
    layout:
      position: beforeBody
      priority: 30
      display: all
layout:
  left:
    - Component: LanguageSwitch
  groups:
    toolbar:
      priority: 20
      direction: row
      gap: 1.25rem
  byPageType:
    "404":
      positions:
        beforeBody: []
        left: []
        right: []
    content: {}
    folder:
      exclude:
        - reader-mode
      positions:
        right: []
    tag:
      exclude:
        - reader-mode
      positions:
        right: []
    canvas: {}
    bases: {}
